import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import ClickSpark from "@/components/ClickSpark";

import { ClerkProvider } from "@clerk/nextjs";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "DeepWeeds Dashboard",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <ClerkProvider
      signInForceRedirectUrl="/dashboard/image-upload"
      signUpForceRedirectUrl="/dashboard/image-upload"
      signInUrl="/sign-in"
      signUpUrl="/sign-up"
    >
      <html lang="de">
        <body
          className={`${geistSans.variable} ${geistMono.variable} antialiased bg-background`}
        >
          <ClickSpark>{children}</ClickSpark>
        </body>
      </html>
    </ClerkProvider>
  );
}
